import localFont from "next/font/local";
import "./globals.css";

import { AppProvider } from "../components/AppProvider";
import Header from "../components/Header";
import Footer from "../components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      // className="min-h-screen flex flex-col"
      >
        <AppProvider>
          <Header />
          <main className="flex-grow mx-auto">
            {children}
          </main>
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
